### ISSUE TITLE
Update repo to generate site after org rename to JuliaDatabases

### ISSUE THREAD

**Issue by non-Jedi** [JuliaDB/juliadb.github.io#1]
Don't entirely know how github pages work, but SQLite.jl at least links to a page under juliadb.github.io which doesn't exist (see https://github.com/JuliaDatabases/SQLite.jl/issues/135). I'm assuming that the reason juliadb.github.io doesn't exist is because the github org changed its name at some point?

**Comment by aviks** [comment]
Should be fixed now.
